
export interface KnowledgeSection {
    id: string;
    title: string;
    content: string;
    keywords: string[];
}

export const KNOWLEDGE_BASE: KnowledgeSection[] = [
    {
        id: "about",
        title: "About Watcharapon",
        content: "Watcharapon (Oat) Thodraksa is a Full-Stack Developer specializing in AI Applications, Mobile Development, and UX/UI Design. He is a Computer Science student (Co-op Program) at Kasetsart University Chalermphrakiat Sakon Nakhon Campus (GPA 2.97), with hands-on enterprise experience from his co-op at Sycapt Co., Ltd. in Bangkok. He can be reached at watcharapon.thod@gmail.com or 094-453-2072.",
        keywords: ["who", "biography", "background", "location", "bangkok", "contact", "email", "phone", "education", "university"]
    },
    {
        id: "philosophy",
        title: "Engineering Philosophy",
        content: "Watcharapon's core philosophy: 1. Clarity over Cleverness — readable, maintainable code over obscure abstractions; a system is only as good as its weakest link. 2. Impact-Driven Engineering — every technical decision (database schema, infrastructure) must serve a clear user need and advance business goals. 3. Constraint-Driven Innovation — his best work often came from hard constraints, like fitting 4 LLMs into 16GB VRAM.",
        keywords: ["philosophy", "coding style", "principles", "thinking", "approach"]
    },
    {
        id: "skills-core",
        title: "Core Technical Skills",
        content: "Full-Stack: React, Next.js, NestJS, FastAPI, Python, TypeScript, Java Spring Boot, Node.js, PHP. Mobile: React Native + Gemini API. AI/RAG: LangChain, LangGraph, LlamaIndex, pgvector, Qdrant, Gemini API, Hugging Face, n8n, Prompt Engineering. Database: PostgreSQL, MySQL, MongoDB, Firebase, Redis. DevOps: Docker, Kubernetes, GitLab CI/CD, Apache Kafka, ELK Stack, Prometheus, Grafana. Design: Figma, Canva, Power BI. Security: Penetration Testing, Vulnerability Analysis, Defensive Tool Development.",
        keywords: ["skills", "languages", "tools", "stack", "tech", "react", "python", "langchain", "kubernetes", "docker"]
    },
    {
        id: "projects-rag-chat",
        title: "Project: RAG Chat — WebClient AI Workspace",
        content: "rag-chat is an enterprise agentic RAG chat platform for document retrieval and bug tracking, powered by LangGraph and Ollama. It runs 100% on-premises — no data leaves the building. The system works in 3 stages: Pre-Retrieval (query intent analysis + HyDE query expansion), Hybrid Retrieval (pgvector cosine similarity + full-text search + dynamic SQL generation for Mantis bug tracker), and Post-Retrieval (cross-encoder re-ranking). LangGraph state-machine routes between document search, image retrieval, and live SQL depending on query intent. Multi-user session management with per-department document scoping. Dynamic GPU model swapping runs 4 LLMs concurrently on 16GB VRAM by cycling models between GPU and RAM. Every reasoning step streams to the client via SSE. Stack: LangGraph, LangChain, Ollama, React, Node.js, PostgreSQL + pgvector, GitLab CI/CD + Kubernetes. GitHub: https://github.com/watcharaponthod-code/rag-chat",
        keywords: ["project", "rag", "chat", "rag-chat", "langgraph", "langchain", "ollama", "vector", "hybrid", "retrieval", "on-premises", "sql", "mantis", "bug tracker", "streaming", "sse", "agentic"]
    },
    {
        id: "projects-embedding-rag",
        title: "Project: embedding_rag — Vector Document Knowledge Base",
        content: "embedding_rag is an enterprise document management and intelligent knowledge retrieval system. Documents (PDF, Word, images) are ingested through 3 pipelines: manual upload, automated email capture via n8n webhooks, and pre-processed data from an external embedding service. Each document is chunked and embedded using BGE-M3 (1024-dimensional, cross-lingual Thai/English). Images within documents are described by a vision model and embedded separately, enabling image-aware retrieval. At query time: vector cosine similarity (pgvector) and PostgreSQL full-text search run in parallel, merged by Reciprocal Rank Fusion (RRF), then re-scored by BGE-Reranker-v2-m3 cross-encoder. Final answer generated by self-hosted Llama3/Qwen via Ollama. Responses include source citations showing which file and section the information came from. All responses stream in real-time. Zero external API calls. Stack: TypeScript, PostgreSQL + pgvector, LlamaIndex, LangChain, React. GitHub: https://github.com/watcharaponthod-code/embedding_rag",
        keywords: ["project", "embedding", "rag", "embedding_rag", "vector", "bge", "pgvector", "hybrid", "reranker", "rrf", "citation", "document", "knowledge base", "on-premises", "llamaindex", "ingestion"]
    },
    {
        id: "projects-bitcoin-ml",
        title: "Project: bitcoin-ml-prediction — Bitcoin Price Prediction",
        content: "bitcoin-ml-prediction is a machine learning project for Bitcoin price prediction using LSTM, XGBoost, and Random Forest ensemble trained on 12 years of BTC-USD OHLCV data (2013–2025, 4,200+ samples). LSTM handles continuous price regression with a 90-day lookback window; XGBoost and Random Forest handle directional classification. LSTM architecture: 3 stacked layers (128→64→32), Dropout(0.2), Huber loss for outlier robustness. Result: 87.81% accuracy (MAPE-based), MAE $2,847, RMSE $5,219 on held-out test data. 18 engineered technical indicators: trend (MA7/30/50, EMA12/26), momentum, volatility (Bollinger Bands), oscillators (RSI, MACD), and volume ratios. Top XGBoost features by importance: RSI, MACD Histogram, 7-day Volatility. GitHub: https://github.com/watcharaponthod-code/bitcoin-ml-prediction",
        keywords: ["project", "bitcoin", "ml", "machine learning", "lstm", "xgboost", "random forest", "prediction", "crypto", "trading", "deep learning", "time series", "technical indicators", "rsi", "macd"]
    },
    {
        id: "projects-ninja-fruit",
        title: "Project: Ninja Fruit — Body-Controlled Fruit Slash Game",
        content: "Ninja_fruit is a Fruit Ninja-style game controlled entirely by body movement using a webcam — no controller needed. YOLOv8 Pose (yolov8n-pose.pt) detects 17 keypoints and tracks up to 3 players simultaneously, assigning each by horizontal position. Hand History Buffer stores 6 frames of wrist keypoints per player. When wrist displacement exceeds 15px, a slash vector is emitted and checked against all active fruit/bomb hitboxes using line-segment to circle distance. Score: +1 per fruit, combo bonus every 3 cuts, -5 for bombs. Particle effects on every cut. 60-second countdown composited over live webcam feed at 30+ FPS via Pygame. Stack: Python, YOLOv8, OpenCV, Pygame. GitHub: https://github.com/watcharaponthod-code/Ninja_fruit",
        keywords: ["project", "ninja", "fruit", "ninja_fruit", "yolo", "yolov8", "pose", "detection", "game", "webcam", "computer vision", "pygame", "opencv", "body", "gesture"]
    },
    {
        id: "projects-subway-kids",
        title: "Project: Subway Kids — Body-Controlled Endless Runner",
        content: "subway-kids is a Subway Surfers-style endless runner controlled by body gestures via webcam. MediaPipe Pose Lite detects 33 landmarks at 60 FPS with less than 10ms CPU inference. Lane control: hip-centre x < 0.38 = Left, 0.38–0.62 = Centre, > 0.62 = Right. Jump: nose y < 0.30. Debounce 200ms prevents false positives. Two modes: Local Pygame at 60 FPS, or Web mode where the browser streams frames over WebSocket to a FastAPI server which returns lane/jump commands. Fully Dockerised with docker-compose. Stack: Python, MediaPipe, Pygame, FastAPI, Docker, TypeScript. GitHub: https://github.com/watcharaponthod-code/subway-kids",
        keywords: ["project", "subway", "kids", "subway-kids", "mediapipe", "pose", "game", "webcam", "endless runner", "pygame", "fastapi", "docker", "body", "gesture", "computer vision"]
    },
    {
        id: "projects-trading",
        title: "Project: AlgoTrade Dashboard — Algorithmic Trading Platform",
        content: "trading is a full-stack algorithmic trading dashboard built with Next.js and TypeScript. Features live WebSocket price feeds, interactive performance charts, algorithm status monitoring, strategy P&L breakdowns, and backtesting result visualizations. Chart components use canvas-based rendering for smooth 60 FPS updates even with high-frequency tick data. Designed for real-time monitoring of multiple trading strategies simultaneously. Stack: Next.js 16, TypeScript, Tailwind CSS, WebSocket, React. GitHub: https://github.com/watcharaponthod-code/trading",
        keywords: ["project", "trading", "algotrade", "algorithmic", "dashboard", "nextjs", "typescript", "websocket", "charts", "fintech", "backtesting"]
    },
    {
        id: "projects-elic",
        title: "Project: ELIC — AI English Learning Chatbot Mobile App",
        content: "ELIC (English Language Improvement Chatbot) is an AI-powered mobile application for Thai-speaking English learners. Users select a conversation role (hotel check-in, restaurant, job interview, medical consultation, meeting new people, taxi) and chat with a role-aware AI tutor powered by Google Gemini. Every Gemini response is parsed into 3 components: conversational reply, vocabulary table (English/Thai/example), and spelling/grammar correction with alternative phrasings. Text-to-speech via expo-speech or a Python FastAPI TTS server backed by Gemini's voice API. Three gamified exercises: Word Game (valid English word from random letter, validated by Gemini), Translation Game (Thai sentence scored by Gemini), Match Game (vocabulary pairing). Scores persisted to Firebase Realtime Database with a live leaderboard. Authentication via Firebase Auth with AsyncStorage offline caching. This was Watcharapon's capstone senior project at Kasetsart University — his first LLM-powered production app, which shaped his understanding of response latency, cost-per-request, and prompt engineering. Stack: React Native 0.76.9, Expo ~52.0, Google Gemini API (gemini-2.0-flash), Firebase (Auth + Firestore + Realtime DB), FastAPI TTS, GitHub Actions CI/CD + EAS Build. GitHub: https://github.com/watcharaponthod-code/elic",
        keywords: ["project", "elic", "english", "learning", "chatbot", "mobile", "react native", "expo", "gemini", "firebase", "tts", "capstone", "game", "translation", "grammar", "vocabulary", "thai"]
    },
    {
        id: "projects-sycapt-ai",
        title: "Project: Sycapt AI Enterprise (Co-op)",
        content: "Built Sycapt AI Enterprise — a 100% on-premises corporate knowledge management system at Sycapt Co., Ltd. Accepts PDF/DOCX/PPTX, converts to vectors using bge-m3 model, then allows natural language queries. Features Agentic RAG Pipeline (LangChain, LangGraph, LlamaIndex) with Hybrid Search (Vector + Full-Text) and Re-ranking. Deployed on Kubernetes. Tech: Next.js, NestJS, Python, pgvector, LangGraph, Kubernetes. (2025)",
        keywords: ["project", "rag", "enterprise", "sycapt", "vector", "ai", "llm", "knowledge", "management", "on-premises"]
    },
    {
        id: "projects-gpu-vram",
        title: "Project: GPU VRAM Optimization (Model Swapping)",
        content: "Solved a critical GPU VRAM constraint at Sycapt: only 16GB VRAM available but needed to run 4 different LLMs. Designed a Model Swapping system that cycles models in/out of VRAM, using 120GB RAM as a buffer pool. This allowed running multiple specialized models without hardware upgrades.",
        keywords: ["gpu", "vram", "optimization", "model swapping", "llm", "memory", "hardware"]
    },
    {
        id: "projects-edc-map",
        title: "Project: EDC Geo Map Dashboard (Co-op)",
        content: "Built a web application visualizing 15,423 Bangkok Bank EDC (Electronic Data Capture) machines nationwide on an interactive map. Features real-time filtering by province, region, machine type, and status. Supports CSV export. Tech: FastAPI, SQLAlchemy, Leaflet.js, Chart.js, PostgreSQL. (Sycapt, 2025)",
        keywords: ["project", "edc", "map", "geo", "dashboard", "leaflet", "visualization", "bangkok bank", "geospatial"]
    },
    {
        id: "projects-kafka-connector",
        title: "Project: VHQ SOM Connector Microservice (Co-op)",
        content: "Developed a microservice connecting Kafka message queues to VHQ API using Event-Driven Architecture. 3-phase flow: receive job → send batch → return result. Uses ELK Stack for centralized logging. Tech: Java 21, Spring Boot, Apache Kafka, PostgreSQL, Docker. (Sycapt, 2025)",
        keywords: ["project", "kafka", "microservice", "event-driven", "java", "spring boot", "connector", "vhq"]
    },
    {
        id: "projects-cicd",
        title: "Project: GitLab CI/CD Pipeline Design (Co-op)",
        content: "Designed a complete CI/CD Pipeline on GitLab CI: Build → Test → Docker Build → Deploy Staging → Deploy Production with Auto Rollback on Kubernetes. Ensures zero-downtime deployments and fast rollback on failures. (Sycapt, 2025)",
        keywords: ["cicd", "gitlab", "pipeline", "kubernetes", "docker", "devops", "deployment", "automation"]
    },
    {
        id: "projects-mobile-workshop",
        title: "Project: React Native AI App (Workshop)",
        content: "Built a mobile application connecting to Gemini API for AI features on iOS/Android, developed as educational material for a university workshop at Kasetsart University Chalermphrakiat. Received 7,500 THB speaking fee. Also taught Git/GitHub workshop (5,000 THB). Tech: React Native, Gemini API, JavaScript.",
        keywords: ["project", "mobile", "react native", "gemini", "workshop", "teaching", "lecture", "university"]
    },
    {
        id: "projects-freelance",
        title: "Project: Donlaya Makeup Portfolio Website (Freelance)",
        content: "Freelance project: built a portfolio website for a makeup artist (Donlaya Makeup) via Fastwork platform. Fully responsive design, delivered on-time within 3,000 THB budget. Tech: Next.js, React, TypeScript, Tailwind CSS. (2024)",
        keywords: ["project", "freelance", "website", "portfolio", "makeup", "nextjs", "tailwind"]
    },
    {
        id: "awards",
        title: "Awards & Competitions",
        content: "🥈 2nd Place Runner-Up — KUSE AI Hackathon 2025: Built AI system in 3 days using Machine Learning, Prompt Engineering, and Design Thinking. 🏆 UI Design-athon 2025: UI design competition using JTBD and Business Model Canvas. 🔐 RERU Cyber Hackathon 2025 (Open Level): Penetration testing, vulnerability analysis, and defensive tool development.",
        keywords: ["award", "hackathon", "competition", "prize", "achievement", "kuse", "reru", "design"]
    },
    {
        id: "experience-sycapt",
        title: "Work Experience: Sycapt Co., Ltd.",
        content: "Software Developer (Co-op Internship) at Sycapt Co., Ltd., Bangkok — January to May 2025. Developed full-stack Sycapt AI Enterprise on Kubernetes, built Agentic RAG Pipeline, solved GPU VRAM constraints, created EDC Geo Map, developed Kafka microservice connector, and designed CI/CD pipeline with auto rollback.",
        keywords: ["experience", "work", "sycapt", "job", "internship", "co-op", "company"]
    }
];

/**
 * Simple Retrieval Function
 * In a real app, this would use Vector Search.
 * Here we use keyword matching as a lightweight alternative.
 */
export function getRelevantContext(query: string): string {
    const lowercaseQuery = query.toLowerCase();

    // Search for the most relevant sections based on keywords
    const relevantSections = KNOWLEDGE_BASE.filter(section =>
        section.keywords.some(keyword => lowercaseQuery.includes(keyword)) ||
        section.title.toLowerCase().includes(lowercaseQuery)
    );

    if (relevantSections.length === 0) {
        // Return a general overview if no specific match is found
        return KNOWLEDGE_BASE.find(s => s.id === "about")?.content || "";
    }

    return relevantSections.map(s => s.content).join("\n\n");
}
