import ProjectDetail, { type ProjectDetailData } from './ProjectDetail';

// One page per detector in the sugarcane-cv repository. Facts and wording come
// from the repo README; nothing here is claimed beyond what the README states.
const RAW = 'https://raw.githubusercontent.com/watcharaponthod-code/sugarcane-cv/main';

export const SCV_PAGES: Record<string, ProjectDetailData> = {
  'scv-1': {
    id: "scv-1",
    title: "Sugarcane CV 1/9: Burnt vs Fresh Cane",
    role: "DL · COMPUTER VISION",
    year: '2026',
    tagline: "whether the load on a truck is burnt cane or fresh cane. Some farmers burn the field before cutting; burnt cane is paid less at the weighbridge, so grading each truck has direct commercial value.",
    overview: "What it detects: whether the load on a truck is burnt cane or fresh cane. Some farmers burn the field before cutting; burnt cane is paid less at the weighbridge, so grading each truck has direct commercial value. Method: a trained image classifier, EfficientNet-B0 at 384 px, 6 epochs, 5-fold cross-validation. Data: 8,612 real CCTV frames from the mill, 4 classes, 6 days, 2 cameras (MPDC00 and MPK00), from the public Roboflow dataset aimlsugarcane (CC BY 4.0). This data broke the whole earlier pipeline: everything built before assumed burnt cane is glossy black and fresh cane is green. Real burnt cane is neither. What actually separates them is whether leaves are still attached plus a dry, pale surface, so all synthetic training data and every colour rule derived from it were thrown out. Evidence: mean over 5 folds, recall 0.873 ±0.117, precision 0.843 ±0.108, accuracy 0.9586 ±0.0069; worst fold recall 0.711, precision 0.658, accuracy 0.9500. Mean F1 0.854 against a camera-only baseline of 0.417. Caveat stated up front: class and camera are almost perfectly confounded. 94 percent of burnt samples come from one camera and 79 percent of fresh from the other, so the model can score well by learning which camera took the picture. Measured per camera, recall is 0.944 on MPDC00 and 0.415 on MPK00. The lower number is the more honest one, and it is why every result in the repo is reported per camera. Status: works, but camera-bound.",
    sections: [
      { title: "How it works", body: "a trained image classifier, EfficientNet-B0 at 384 px, 6 epochs, 5-fold cross-validation.", image: `${RAW}/figures/real_burnt_cane.jpg`, imageCaption: "REAL BURNT CANE // greyish-brown, pale, dry dull stalks, leaves burnt off. Not black, not glossy", fullWidth: true },
      { title: "Training data", body: "8,612 real CCTV frames from the mill, 4 classes, 6 days, 2 cameras (MPDC00 and MPK00), from the public Roboflow dataset aimlsugarcane (CC BY 4.0). This data broke the whole earlier pipeline: everything built before assumed burnt cane is glossy black and fresh cane is green. Real burnt cane is neither. What actually separates them is whether leaves are still attached plus a dry, pale surface, so all synthetic training data and every colour rule derived from it were thrown out." },
      { title: "Evidence", body: "mean over 5 folds, recall 0.873 ±0.117, precision 0.843 ±0.108, accuracy 0.9586 ±0.0069; worst fold recall 0.711, precision 0.658, accuracy 0.9500. Mean F1 0.854 against a camera-only baseline of 0.417. Caveat stated up front: class and camera are almost perfectly confounded. 94 percent of burnt samples come from one camera and 79 percent of fresh from the other, so the model can score well by learning which camera took the picture. Measured per camera, recall is 0.944 on MPDC00 and 0.415 on MPK00. The lower number is the more honest one, and it is why every result in the repo is reported per camera." },
      { title: "Status and limits", body: "works, but camera-bound." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["PyTorch", "EfficientNet-B0", "ONNX", "OpenCV"],
    metrics: [{"label": "REAL CCTV FRAMES", "value": "8,612"}, {"label": "MEAN F1 (5 FOLDS)", "value": "0.854"}, {"label": "RECALL PER CAMERA", "value": "0.944 / 0.415"}, {"label": "STATUS", "value": "CAMERA-BOUND"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-2': {
    id: "scv-2",
    title: "Sugarcane CV 2/9: Burnt Cane Mixed into a Load",
    role: "RULE-BASED · COMPUTER VISION",
    year: '2026',
    tagline: "what share of the visible top surface of a load is burnt cane. A truck is rarely all-burnt or all-fresh; the question is how much burnt cane on the surface should flip the grade.",
    overview: "What it detects: what share of the visible top surface of a load is burnt cane. A truck is rarely all-burnt or all-fresh; the question is how much burnt cane on the surface should flip the grade. Method: no model. The detector counts bright stalks, because a burnt pile has almost none. Two candidate colour statistics were tested on simulated mixes (burnt surface pixels composited onto a fresh pile, both scattered in patches and as one continuous layer). black% fails: fresh cane in the shadow of the truck bed measures 36.6 percent dark and burnt cane 43 to 60 percent, so the ranges overlap and texture filtering does not separate them. bright% works: burnt piles have 0.6 to 6 percent bright stalks while fresh piles always have some, 19 to 21 percent even in shadow, a clear 3x gap. Data: two clips only. Evidence: simulated mix images; the README gives no accuracy figure. Limitations as written: the 8/15 thresholds are provisional, derived from only two clips, and must be re-set on real footage; the frame must be taken after the bed is raised or once the dust has settled, because dust brightens the pile enough to break the rule. Status: rule found, threshold not set.",
    sections: [
      { title: "How it works", body: "no model. The detector counts bright stalks, because a burnt pile has almost none. Two candidate colour statistics were tested on simulated mixes (burnt surface pixels composited onto a fresh pile, both scattered in patches and as one continuous layer). black% fails: fresh cane in the shadow of the truck bed measures 36.6 percent dark and burnt cane 43 to 60 percent, so the ranges overlap and texture filtering does not separate them. bright% works: burnt piles have 0.6 to 6 percent bright stalks while fresh piles always have some, 19 to 21 percent even in shadow, a clear 3x gap.", image: `${RAW}/figures/burn_mix_30pct_scattered.jpg`, imageCaption: "SIMULATED MIX // burnt surface pixels composited onto a fresh pile, 30 percent, scattered in patches", fullWidth: true },
      { title: "Training data", body: "two clips only." },
      { title: "Evidence", body: "simulated mix images; the README gives no accuracy figure. Limitations as written: the 8/15 thresholds are provisional, derived from only two clips, and must be re-set on real footage; the frame must be taken after the bed is raised or once the dust has settled, because dust brightens the pile enough to break the rule." },
      { title: "Status and limits", body: "rule found, threshold not set." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["OpenCV", "NumPy"],
    metrics: [{"label": "MODEL", "value": "NONE"}, {"label": "TEST SET", "value": "SIMULATED MIXES"}, {"label": "RULE", "value": "FOUND"}, {"label": "CUT-OFF", "value": "NOT SET"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-3': {
    id: "scv-3",
    title: "Sugarcane CV 3/9: Dirt, Tops and Leaf Trash",
    role: "DL · SEGMENTATION",
    year: '2026',
    tagline: "what share of the load is soil, cane tops and leaf trash instead of millable cane. The mill does not want to pay for dirt.",
    overview: "What it detects: what share of the load is soil, cane tops and leaf trash instead of millable cane. The mill does not want to pay for dirt. Method: a trained segmentation model (the README names no architecture; the training scripts live in src/dirty_area). Data: 65 original real images, expanded by Roboflow augmentation to 158; the true unit count is 54 trucks. Result: inconclusive, and the reasons are recorded rather than hidden. The sugar-cane class has zero annotations across all 158 images, so the \"fraction of the pile\" cannot be computed at all; only dirty ÷ (dirty + labelled clean area) can, and that depends on how wide each annotator drew their boxes. The published split leaks: one original image appears three times in train and once in valid, which is 10 percent of a 10-image validation set. The cross-camera score of 0.842 is exactly equal to a baseline that always guesses the majority class, meaning the model learned nothing. The README is explicit that this does not mean the problem is unsolvable, only that 65 images cannot decide it. Status: inconclusive, data-limited.",
    sections: [
      { title: "How it works", body: "a trained segmentation model (the README names no architecture; the training scripts live in src/dirty_area).", image: `${RAW}/figures/dirty_area_labels.jpg`, imageCaption: "DIRTY-AREA LABELS // annotation overview. The labelling standard itself is the bottleneck", fullWidth: true },
      { title: "Training data", body: "65 original real images, expanded by Roboflow augmentation to 158; the true unit count is 54 trucks. Result: inconclusive, and the reasons are recorded rather than hidden. The sugar-cane class has zero annotations across all 158 images, so the \"fraction of the pile\" cannot be computed at all; only dirty ÷ (dirty + labelled clean area) can, and that depends on how wide each annotator drew their boxes. The published split leaks: one original image appears three times in train and once in valid, which is 10 percent of a 10-image validation set. The cross-camera score of 0.842 is exactly equal to a baseline that always guesses the majority class, meaning the model learned nothing. The README is explicit that this does not mean the problem is unsolvable, only that 65 images cannot decide it." },
      { title: "Status and limits", body: "inconclusive, data-limited." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["PyTorch", "Segmentation"],
    metrics: [{"label": "REAL IMAGES", "value": "65"}, {"label": "LABELS", "value": "HAND-MADE"}, {"label": "STATUS", "value": "INCONCLUSIVE"}, {"label": "LIMIT", "value": "DATA"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-4': {
    id: "scv-4",
    title: "Sugarcane CV 4/9: Is There Cane on the Truck",
    role: "RULE-BASED · COMPUTER VISION",
    year: '2026',
    tagline: "before anything else, a side camera decides whether the incoming truck is loaded or empty and triggers the front camera to capture a paired shot.",
    overview: "What it detects: before anything else, a side camera decides whether the incoming truck is loaded or empty and triggers the front camera to capture a paired shot. Method: no trained model for the decision. It fuses classical feature cues (edges and motion) with a tracker, and a pinned test set keeps the Python and browser versions numerically identical. Truck localisation in the same pipeline uses a YOLO11n detector in a web worker, but it runs only occasionally and is not part of the loaded-or-empty decision. Everything runs fully offline at the weighbridge. Evidence: timings measured on CPU with no GPU. Computer vision (motion + tracker), every frame: 3.9 ms, headroom to roughly 250 fps. Truck localisation (YOLO11n, web worker), occasional: 280 ms. Cane decision (cue + fusion), once per truck: 9 ms. Plate read (ONNX + verification), once per truck: 0.2 to 2.5 s. The README gives no detection accuracy figure for this stage. Status: installed and in use on site, 3.9 ms per frame.",
    sections: [
      { title: "How it works", body: "no trained model for the decision. It fuses classical feature cues (edges and motion) with a tracker, and a pinned test set keeps the Python and browser versions numerically identical. Truck localisation in the same pipeline uses a YOLO11n detector in a web worker, but it runs only occasionally and is not part of the loaded-or-empty decision. Everything runs fully offline at the weighbridge.", image: `${RAW}/figures/canegate_live.png`, imageCaption: "CANE GATE LIVE // the pipeline running at the weighbridge, from truck localisation to the loaded-or-empty call", fullWidth: true },
      { title: "Evidence", body: "timings measured on CPU with no GPU. Computer vision (motion + tracker), every frame: 3.9 ms, headroom to roughly 250 fps. Truck localisation (YOLO11n, web worker), occasional: 280 ms. Cane decision (cue + fusion), once per truck: 9 ms. Plate read (ONNX + verification), once per truck: 0.2 to 2.5 s. The README gives no detection accuracy figure for this stage." },
      { title: "Status and limits", body: "installed and in use on site, 3.9 ms per frame." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["OpenCV", "YOLO11n", "Raspberry Pi"],
    metrics: [{"label": "PER FRAME", "value": "3.9 MS"}, {"label": "MODEL FOR DECISION", "value": "NONE"}, {"label": "STATUS", "value": "ON SITE"}, {"label": "TRIGGERS", "value": "FRONT CAMERA"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-5': {
    id: "scv-5",
    title: "Sugarcane CV 5/9: Dust Opacity While Tipping",
    role: "DL + RULE · COMPUTER VISION",
    year: '2026',
    tagline: "how thick the dust cloud is as a truck tips, scored per tipping bay and written to an event log, to trigger water spray and feed environmental reporting.",
    overview: "What it detects: how thick the dust cloud is as a truck tips, scored per tipping bay and written to an event log, to trigger water spray and feed environmental reporting. Method: a trained model plus a hand-written rule. LR-ASPP segmentation with a density head (cut-off 0.29) marks which pixels are dust; then a zone-evidence veto weights each bay's detected% by the fraction of pixels that actually look like airborne dust. That single rule removes false alerts from dark static cane piles and truck beds without retraining the model. The opacity equation itself was checked in simulation before any model existed. Data and evidence: a synthetic test set. The README states the limitation bluntly: the scored test set contains not one real photograph with dust in it. All positive examples are AI-generated, and the only two real images are empty yards that were already used in training. Every recall figure is therefore a test of the pipeline logic on synthetic input, not field accuracy; the README does not publish those recall numbers. The demo clips are public footage, run qualitatively, and count towards no score. A trustworthy false-alert rate still needs fresh empty-yard footage the model has never seen. Status: in use, but not yet verified against real dust.",
    sections: [
      { title: "How it works", body: "a trained model plus a hand-written rule. LR-ASPP segmentation with a density head (cut-off 0.29) marks which pixels are dust; then a zone-evidence veto weights each bay's detected% by the fraction of pixels that actually look like airborne dust. That single rule removes false alerts from dark static cane piles and truck beds without retraining the model. The opacity equation itself was checked in simulation before any model existed. Data and evidence: a synthetic test set. The README states the limitation bluntly: the scored test set contains not one real photograph with dust in it. All positive examples are AI-generated, and the only two real images are empty yards that were already used in training. Every recall figure is therefore a test of the pipeline logic on synthetic input, not field accuracy; the README does not publish those recall numbers. The demo clips are public footage, run qualitatively, and count towards no score. A trustworthy false-alert rate still needs fresh empty-yard footage the model has never seen.", image: `${RAW}/media/dust_base_vs_veto.gif`, imageCaption: "BASE MODEL VS VETO // same clip. The bare model alerts on the dark cane pile; the vetoed model does not", fullWidth: true },
      { title: "Status and limits", body: "in use, but not yet verified against real dust." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["LR-ASPP", "PyTorch", "OpenCV"],
    metrics: [{"label": "SEGMENTATION", "value": "LR-ASPP"}, {"label": "VETO", "value": "HAND RULE"}, {"label": "TEST SET", "value": "SYNTHETIC"}, {"label": "REAL DUST", "value": "NOT SCORED"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-6': {
    id: "scv-6",
    title: "Sugarcane CV 6/9: Sand, Rock and Metal by Sound",
    role: "DL · AUDIO",
    year: '2026',
    tagline: "sand, stones and metal hidden in the pile, which damage the shredder. A camera cannot see inside the load, but a microphone hears the impact when it hits the conveyor.",
    overview: "What it detects: sand, stones and metal hidden in the pile, which damage the shredder. A camera cannot see inside the load, but a microphone hears the impact when it hits the conveyor. Method: a trained model on audio. Sound is converted to a log-mel spectrogram and a small CNN reads it. Training data: impact and sand sounds were generated with Stable Audio Open on a GTX 1060, filtered through acceptance criteria (1 to 10 kHz band energy ≥ 0.35, attack ≤ 20 ms, decay ≤ 800 ms, peak/mean ≥ 6), then mixed onto real background audio recorded at the tipping yard at SNR +12 down to −12 dB with millisecond-level ground truth. 57 clips generated, 30 passed the criteria, 80 test clips, 418 events in total. Evidence, tested on real tipping-bay audio the model had never heard. Energy-threshold rule: impact recall/precision 0.58/0.25, sand 0.35/n/a, 7.6 false alerts per minute. CNN with 0.5 s window: impact 0.47/0.59, sand 0.94/1.00, 2.2 false alerts per minute. CNN with 0.25 s window: impact 0.59/0.35, sand 0.98/0.995, 7.2 false alerts per minute. The README calls sand solved: 94 to 98 percent recall at near-perfect precision on real audio, the strongest result in the project. The CNN beats the plain rule by 2.4x on precision and cuts false alerts 3.5x, because it learned not to react to cane hitting the rails, chains and hammers. Impacts (rock and metal) are not claimed as solved: recall sits at 0.47 to 0.59. No figure for this detector exists in the repo. Status: sand solved; impacts still open.",
    sections: [
      { title: "How it works", body: "a trained model on audio. Sound is converted to a log-mel spectrogram and a small CNN reads it." },
      { title: "Training data", body: "impact and sand sounds were generated with Stable Audio Open on a GTX 1060, filtered through acceptance criteria (1 to 10 kHz band energy ≥ 0.35, attack ≤ 20 ms, decay ≤ 800 ms, peak/mean ≥ 6), then mixed onto real background audio recorded at the tipping yard at SNR +12 down to −12 dB with millisecond-level ground truth. 57 clips generated, 30 passed the criteria, 80 test clips, 418 events in total. Evidence, tested on real tipping-bay audio the model had never heard. Energy-threshold rule: impact recall/precision 0.58/0.25, sand 0.35/n/a, 7.6 false alerts per minute. CNN with 0.5 s window: impact 0.47/0.59, sand 0.94/1.00, 2.2 false alerts per minute. CNN with 0.25 s window: impact 0.59/0.35, sand 0.98/0.995, 7.2 false alerts per minute. The README calls sand solved: 94 to 98 percent recall at near-perfect precision on real audio, the strongest result in the project. The CNN beats the plain rule by 2.4x on precision and cuts false alerts 3.5x, because it learned not to react to cane hitting the rails, chains and hammers. Impacts (rock and metal) are not claimed as solved: recall sits at 0.47 to 0.59. No figure for this detector exists in the repo." },
      { title: "Status and limits", body: "sand solved; impacts still open." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["log-mel CNN", "soundfile", "Stable Audio Open"],
    metrics: [{"label": "SENSOR", "value": "MICROPHONE"}, {"label": "AUDIO", "value": "REAL TIPPING BAY"}, {"label": "SAND", "value": "SOLVED"}, {"label": "IMPACT RECALL", "value": "0.47–0.59"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-7': {
    id: "scv-7",
    title: "Sugarcane CV 7/9: Cane Flow on the Conveyor",
    role: "DL · SELF-TRAINING",
    year: '2026',
    tagline: "the share of leaf on the moving sheet of cane, giving a continuous quality signal instead of one still image per truck.",
    overview: "What it detects: the share of leaf on the moving sheet of cane, giving a continuous quality signal instead of one still image per truck. Method: a self-training segmentation model. Labels start from a small hand-made set and the model then labels further frames itself; the training and self-training scripts are in src/cane_flow (the README does not name the architecture, and the script names there are the only hint that it is YOLO-based). Data and evidence: real video from inside the mill. The published number is speed, not accuracy: 69.9 fps sustained end to end on real in-mill video. The README gives no leaf-share accuracy figure and says the interesting constraint of this task was speed, because the belt never stops and the segmenter has to keep pace on existing equipment. Status: running at 70 fps on real video; accuracy not reported.",
    sections: [
      { title: "How it works", body: "a self-training segmentation model. Labels start from a small hand-made set and the model then labels further frames itself; the training and self-training scripts are in src/cane_flow (the README does not name the architecture, and the script names there are the only hint that it is YOLO-based). Data and evidence: real video from inside the mill. The published number is speed, not accuracy: 69.9 fps sustained end to end on real in-mill video. The README gives no leaf-share accuracy figure and says the interesting constraint of this task was speed, because the belt never stops and the segmenter has to keep pace on existing equipment.", image: `${RAW}/media/caneflow_real.gif`, imageCaption: "CANE FLOW // leaf-area segmentation on real in-mill video with live fresh-percentage readout, 69.9 fps sustained", fullWidth: true },
      { title: "Status and limits", body: "running at 70 fps on real video; accuracy not reported." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["YOLO", "Self-training", "OpenCV"],
    metrics: [{"label": "SPEED", "value": "70 FPS"}, {"label": "VIDEO", "value": "REAL MILL"}, {"label": "LABELS", "value": "SEED + SELF-TRAINED"}, {"label": "SIGNAL", "value": "LEAF SHARE"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-8': {
    id: "scv-8",
    title: "Sugarcane CV 8/9: Thai Licence Plate OCR",
    role: "DL + RULE · OCR",
    year: '2026',
    tagline: "the number plate of the truck on the weighbridge.",
    overview: "What it detects: the number plate of the truck on the weighbridge. Method: two independent readers. The ONNX + OpenCV reader uses a trained detector, an ONNX reader and cross-frame voting, and exists for accuracy. The pure-CV reader uses morphology, then connected components, then template matching against the standard font; it uses no ML at all, runs on a Raspberry Pi, and every step can be explained. Design rule: if it answers, it must be right. The goal is not to read every truck but to make every row written to the CSV trustworthy. On weak evidence it returns accepted=false with a reason and hands the image to a person; one wrong row costs more than ten manual checks. Data and evidence: strict mode on a 60-image hard set, built by compositing plates onto truck images and degrading them with blur, skew, darkness, glare, noise, JPEG quality 40, small size and an off-template font, run on CPU only. Before tuning: answered 48 of 60, 48 correct, 0 wrong, 12 sent to a human, median 2,236 ms per image. After tuning: answered 51 of 60, 51 correct, 0 wrong, 9 sent to a human, median 182 ms per image. The row that matters is wrong = 0; the send-to-human count is the price of it. The README is explicit that this is a controlled synthetic set for comparing readers and catching code regressions, not field accuracy, which depends on the camera, the light and how dirty the plate is. No figure for this detector exists in the repo. Status: designed for zero wrong reads.",
    sections: [
      { title: "How it works", body: "two independent readers. The ONNX + OpenCV reader uses a trained detector, an ONNX reader and cross-frame voting, and exists for accuracy. The pure-CV reader uses morphology, then connected components, then template matching against the standard font; it uses no ML at all, runs on a Raspberry Pi, and every step can be explained. Design rule: if it answers, it must be right. The goal is not to read every truck but to make every row written to the CSV trustworthy. On weak evidence it returns accepted=false with a reason and hands the image to a person; one wrong row costs more than ten manual checks. Data and evidence: strict mode on a 60-image hard set, built by compositing plates onto truck images and degrading them with blur, skew, darkness, glare, noise, JPEG quality 40, small size and an off-template font, run on CPU only. Before tuning: answered 48 of 60, 48 correct, 0 wrong, 12 sent to a human, median 2,236 ms per image. After tuning: answered 51 of 60, 51 correct, 0 wrong, 9 sent to a human, median 182 ms per image. The row that matters is wrong = 0; the send-to-human count is the price of it. The README is explicit that this is a controlled synthetic set for comparing readers and catching code regressions, not field accuracy, which depends on the camera, the light and how dirty the plate is. No figure for this detector exists in the repo." },
      { title: "Status and limits", body: "designed for zero wrong reads." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["ONNX", "OpenCV", "Cross-frame voting"],
    metrics: [{"label": "READERS", "value": "2"}, {"label": "HARD SET", "value": "60 IMAGES"}, {"label": "WRONG READS", "value": "0"}, {"label": "MODE", "value": "STRICT / ABSTAIN"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
  'scv-9': {
    id: "scv-9",
    title: "Sugarcane CV 9/9: Stalk Segmentation",
    role: "DL · COMPUTER VISION",
    year: '2026',
    tagline: "the outline of each individual cane stalk. On its own this has no business value; it exists so that downstream features (leaf share, stalk length, stacking orientation) can be measured on real stalks instead of guessed from the colour of the whole image.",
    overview: "What it detects: the outline of each individual cane stalk. On its own this has no business value; it exists so that downstream features (leaf share, stalk length, stacking orientation) can be measured on real stalks instead of guessed from the colour of the whole image. Method: a trained model with a frozen DINOv2 backbone and a two-layer head. Data: 31 hand-labelled images. Evidence: the README shows the qualitative output below and gives no metric. Status: supporting work.",
    sections: [
      { title: "How it works", body: "a trained model with a frozen DINOv2 backbone and a two-layer head.", image: `${RAW}/figures/stalk_seg_dino.jpg`, imageCaption: "STALK SEGMENTATION // frozen DINOv2 backbone + two-layer head, trained on 31 hand-labelled images", fullWidth: true },
      { title: "Training data", body: "31 hand-labelled images." },
      { title: "Evidence", body: "the README shows the qualitative output below and gives no metric." },
      { title: "Status and limits", body: "supporting work." },
      { title: "Where it sits", body: "One of nine detectors from the same Thai sugar mill in the sugarcane-cv repository. The repo holds training code and algorithms only: no model files and no customer images. Every number states the evidence it stands on, split by day and by camera rather than by random shuffle, and reported together with coverage.", image: `${RAW}/figures/site_map.svg`, imageCaption: "SITE MAP // WHERE EACH DETECTOR SITS AT THE MILL", fullWidth: true },
    ],
    stack: ["DINOv2", "PyTorch"],
    metrics: [{"label": "HAND LABELS", "value": "31"}, {"label": "FEATURES", "value": "DINOv2"}, {"label": "ROLE", "value": "SUPPORTING"}, {"label": "BUSINESS VALUE", "value": "INDIRECT"}],
    githubLink: 'https://github.com/watcharaponthod-code/sugarcane-cv',
  },
};

export default function SugarcaneDetectorProject({ id }: { id: string }) {
  const data = SCV_PAGES[id] || SCV_PAGES['scv-1'];
  return <ProjectDetail data={data} />;
}
